services:
  cat-app:
    build:
      context: .
    container_name: cat-app
    depends_on:
      - db
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
    networks:
      - cat-net
  db:
    image: mysql:8.0
    container_name: database
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'catCrud'
      MYSQL_USER: 'pahin'
      MYSQL_PASSWORD: 'pass1234'
      MYSQL_ROOT_PASSWORD: 'secret'
    ports:
      - 3306:3306
    volumes:
      - mydb:/var/lib/mysql
    networks:
      - cat-net

  volumes:
    mydb:
      driver: local

  networks:
    cat-net:
      name: cat-net
